[package]
name = "pillar"
version = "0.2.3"
authors = ["flber <benrhammond@gmail.com>"]
edition = "2018"

[dependencies]
toml = "0.5"
regex = "1.5"
lazy_static = "1.4.0"
walkdir = "2"

[profile.release]
debug = true