Token {
    parents: Parents {
        bytes: [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
        ],
        len: 0,
    },
    rune: 63,
    contents: "{}\n\n{}\n\n{}\n\n{}\n\n{}\n{}\n{}\n\n{}\n{}\n\n{}\n\n{}\n\n{}\n{}\n\n{}\n",
    tokens: [
        Token {
            parents: Parents {
                bytes: [
                    63,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                ],
                len: 1,
            },
            rune: 35,
            contents: "Hi",
            tokens: [],
        },
        Token {
            parents: Parents {
                bytes: [
                    63,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                ],
                len: 1,
            },
            rune: 59,
            contents: "I'm Ben, a person (who prefers they/them pronouns) from the bay area, though I go to school in Santa Cruz. I like to make {}, occasionally {}, and tell computers to do things for me (though we often have disagreements).",
            tokens: [
                Token {
                    parents: Parents {
                        bytes: [
                            63,
                            59,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                        ],
                        len: 2,
                    },
                    rune: 64,
                    contents: "food",
                    tokens: [],
                },
                Token {
                    parents: Parents {
                        bytes: [
                            63,
                            59,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                        ],
                        len: 2,
                    },
                    rune: 64,
                    contents: "draw",
                    tokens: [],
                },
            ],
        },
        Token {
            parents: Parents {
                bytes: [
                    63,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                ],
                len: 1,
            },
            rune: 59,
            contents: "I've worked on a few {}, including a {}. When I'm not getting frustrated with computers for not following my every command, I enjoy playing {}, {}, and {}.",
            tokens: [
                Token {
                    parents: Parents {
                        bytes: [
                            63,
                            59,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                        ],
                        len: 2,
                    },
                    rune: 64,
                    contents: "projects",
                    tokens: [],
                },
                Token {
                    parents: Parents {
                        bytes: [
                            63,
                            59,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                        ],
                        len: 2,
                    },
                    rune: 64,
                    contents: "game or two",
                    tokens: [],
                },
                Token {
                    parents: Parents {
                        bytes: [
                            63,
                            59,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                        ],
                        len: 2,
                    },
                    rune: 64,
                    contents: "video games",
                    tokens: [],
                },
                Token {
                    parents: Parents {
                        bytes: [
                            63,
                            59,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                        ],
                        len: 2,
                    },
                    rune: 64,
                    contents: "hiking",
                    tokens: [],
                },
                Token {
                    parents: Parents {
                        bytes: [
                            63,
                            59,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                        ],
                        len: 2,
                    },
                    rune: 64,
                    contents: "reading",
                    tokens: [],
                },
            ],
        },
        Token {
            parents: Parents {
                bytes: [
                    63,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                ],
                len: 1,
            },
            rune: 59,
            contents: "If you want to contact me about commercial work, please first take a look at my {}. Email is generally the best method of communication for me, and you can find my email address linked in the footer.",
            tokens: [
                Token {
                    parents: Parents {
                        bytes: [
                            63,
                            59,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                        ],
                        len: 2,
                    },
                    rune: 64,
                    contents: "resume",
                    tokens: [],
                },
            ],
        },
        Token {
            parents: Parents {
                bytes: [
                    63,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                ],
                len: 1,
            },
            rune: 59,
            contents: "Because I'm not super experienced in any one field, I often find myself anxious those more knowledgeable. That's mostly because I don't want to waste their time, but  I probably end up wasting more time by adding prefaces to my questions, such as:",
            tokens: [],
        },
        Token {
            parents: Parents {
                bytes: [
                    63,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                ],
                len: 1,
            },
            rune: 126,
            contents: "\n\t{}\n\t{}\n\t{}\n\t{}\n",
            tokens: [
                Token {
                    parents: Parents {
                        bytes: [
                            63,
                            126,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                        ],
                        len: 2,
                    },
                    rune: 45,
                    contents: "Sorry to bother you, but...",
                    tokens: [],
                },
                Token {
                    parents: Parents {
                        bytes: [
                            63,
                            126,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                        ],
                        len: 2,
                    },
                    rune: 45,
                    contents: "This may be a simple question, but...",
                    tokens: [],
                },
                Token {
                    parents: Parents {
                        bytes: [
                            63,
                            126,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                        ],
                        len: 2,
                    },
                    rune: 45,
                    contents: "Pardon my lack of knowledge in this, but...",
                    tokens: [],
                },
                Token {
                    parents: Parents {
                        bytes: [
                            63,
                            126,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                        ],
                        len: 2,
                    },
                    rune: 45,
                    contents: "I probably just missed the answer to this in the docs somewhere, but...",
                    tokens: [],
                },
            ],
        },
        Token {
            parents: Parents {
                bytes: [
                    63,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                ],
                len: 1,
            },
            rune: 59,
            contents: "and others. I'll try to just cut to the chase from now on, but if you need some context as to why I'm asking about something you think is simple, please feel free to mentally add one of the above prefaces to the start of my question!",
            tokens: [],
        },
        Token {
            parents: Parents {
                bytes: [
                    63,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                ],
                len: 1,
            },
            rune: 59,
            contents: "You can find the source code for this site in any of these places:",
            tokens: [],
        },
        Token {
            parents: Parents {
                bytes: [
                    63,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                ],
                len: 1,
            },
            rune: 126,
            contents: "\n\t{}\n\t{}\n\t{}\n",
            tokens: [
                Token {
                    parents: Parents {
                        bytes: [
                            63,
                            126,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                        ],
                        len: 2,
                    },
                    rune: 45,
                    contents: "{}",
                    tokens: [
                        Token {
                            parents: Parents {
                                bytes: [
                                    63,
                                    126,
                                    45,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                ],
                                len: 3,
                            },
                            rune: 64,
                            contents: "codeberg",
                            tokens: [],
                        },
                    ],
                },
                Token {
                    parents: Parents {
                        bytes: [
                            63,
                            126,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                        ],
                        len: 2,
                    },
                    rune: 45,
                    contents: "{}",
                    tokens: [
                        Token {
                            parents: Parents {
                                bytes: [
                                    63,
                                    126,
                                    45,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                ],
                                len: 3,
                            },
                            rune: 64,
                            contents: "github",
                            tokens: [],
                        },
                    ],
                },
                Token {
                    parents: Parents {
                        bytes: [
                            63,
                            126,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                        ],
                        len: 2,
                    },
                    rune: 45,
                    contents: "{}",
                    tokens: [
                        Token {
                            parents: Parents {
                                bytes: [
                                    63,
                                    126,
                                    45,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                ],
                                len: 3,
                            },
                            rune: 64,
                            contents: "srht",
                            tokens: [],
                        },
                    ],
                },
            ],
        },
        Token {
            parents: Parents {
                bytes: [
                    63,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                ],
                len: 1,
            },
            rune: 59,
            contents: "You can check out the {} page for a list of the hardware and software I use.",
            tokens: [
                Token {
                    parents: Parents {
                        bytes: [
                            63,
                            59,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                        ],
                        len: 2,
                    },
                    rune: 64,
                    contents: "inventory",
                    tokens: [],
                },
            ],
        },
        Token {
            parents: Parents {
                bytes: [
                    63,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                ],
                len: 1,
            },
            rune: 59,
            contents: "Feel free to say hi on {} or via my {}",
            tokens: [
                Token {
                    parents: Parents {
                        bytes: [
                            63,
                            59,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                        ],
                        len: 2,
                    },
                    rune: 64,
                    contents: "mastodon",
                    tokens: [],
                },
                Token {
                    parents: Parents {
                        bytes: [
                            63,
                            59,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                        ],
                        len: 2,
                    },
                    rune: 64,
                    contents: "email",
                    tokens: [],
                },
            ],
        },
        Token {
            parents: Parents {
                bytes: [
                    63,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                ],
                len: 1,
            },
            rune: 59,
            contents: "I'm also on {}! All the sites on it are pretty neat, including those of my neighbours:",
            tokens: [
                Token {
                    parents: Parents {
                        bytes: [
                            63,
                            59,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                        ],
                        len: 2,
                    },
                    rune: 64,
                    contents: "a webring",
                    tokens: [],
                },
            ],
        },
        Token {
            parents: Parents {
                bytes: [
                    63,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                ],
                len: 1,
            },
            rune: 126,
            contents: "\n\t{}\n\t{}\n",
            tokens: [
                Token {
                    parents: Parents {
                        bytes: [
                            63,
                            126,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                        ],
                        len: 2,
                    },
                    rune: 45,
                    contents: "Alessia Bellisario's {}",
                    tokens: [
                        Token {
                            parents: Parents {
                                bytes: [
                                    63,
                                    126,
                                    45,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                ],
                                len: 3,
                            },
                            rune: 64,
                            contents: "anti/pattern",
                            tokens: [],
                        },
                    ],
                },
                Token {
                    parents: Parents {
                        bytes: [
                            63,
                            126,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                        ],
                        len: 2,
                    },
                    rune: 45,
                    contents: "Martin Schotten's {}",
                    tokens: [
                        Token {
                            parents: Parents {
                                bytes: [
                                    63,
                                    126,
                                    45,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                ],
                                len: 3,
                            },
                            rune: 64,
                            contents: "fragmentscenario",
                            tokens: [],
                        },
                    ],
                },
            ],
        },
        Token {
            parents: Parents {
                bytes: [
                    63,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                ],
                len: 1,
            },
            rune: 59,
            contents: "And finally, here are some fun banners which I've started collecting :3",
            tokens: [],
        },
    ],
}

